name: grocery_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.9
  provider: ^6.1.1
  flutter_easyloading: ^3.0.5
  api_cache_manager: ^1.0.2
  sqflite_common_ffi: ^2.3.0+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
